[versions]
kotlin = "1.7.0"
swiftpack = "0.0.5"
kotest = "5.4.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "3.0.3" }
swiftpack = { id = "co.touchlab.swiftpack", version.ref = "swiftpack" }
swiftkt = { id = "co.touchlab.swiftkt", version = "0.0.11" }

[libraries]

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.6.4" }

swiftpack-api = { module = "co.touchlab.swiftpack:swiftpack-api", version.ref = "swiftpack" }
compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
compiler-testing = { module = "com.github.tschuchortdev:kotlin-compile-testing", version = "1.4.9" }

kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version = "1.12.5" }

[bundles]
testing-jvm = [
    "kotest-runner-junit5",
    "kotest-assertions-core",
    "kotest-framework-datatest",
    "mockk"
]