[versions]
detekt = "1.20.0"
kotlin = "1.7.0"
ktlintGradle = "10.3.0"
pluginPublish = "0.21.0"
versionCheck = "0.42.0"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintGradle" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
versionCheck = { id = "com.github.ben-manes.versions", version.ref = "versionCheck" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "3.0.3" }
shadow = { id = "com.github.johnrengelman.shadow", version = "7.1.2" }

[libraries]
auto-service = { module = "com.google.auto.service:auto-service", version = "1.0" }
junit = "junit:junit:4.13.2"
