[versions]
kotlin = "1.7.10"
swiftpack = "0.0.23"
swiftlink = "0.0.28"
kotest = "5.4.0"
pluginPublish = "1.0.0"

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version = "3.0.3" }
swiftpack = { id = "co.touchlab.swiftpack", version.ref = "swiftpack" }
swiftlink = { id = "co.touchlab.swiftlink", version.ref = "swiftlink" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }

[libraries]
swiftlink-gradle-plugin = { module = "co.touchlab.swiftlink:gradle-plugin", version.ref = "swiftlink" }
swiftlink-plugin = { module = "co.touchlab.swiftlink:plugin", version.ref = "swiftlink" }
swiftlink-plugin-spi = { module = "co.touchlab.swiftlink:plugin-spi", version.ref = "swiftlink" }
swiftpack-gradle-plugin = { module = "co.touchlab.swiftpack:swiftpack-gradle-plugin", version.ref = "swiftpack" }
swiftpack-api = { module = "co.touchlab.swiftpack:swiftpack-api", version.ref = "swiftpack" }
swiftpack-spi = { module = "co.touchlab.swiftpack:swiftpack-spi", version.ref = "swiftpack" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.4.0" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
mockk = { module = "io.mockk:mockk", version = "1.12.5" }

[bundles]
testing-jvm = [
    "kotlin-test",
    "kotest-runner-junit5",
    "kotest-assertions-core",
    "kotest-framework-datatest",
    "mockk"
]
