name: Compare Pure and SKIE

on:
  workflow_dispatch:
    inputs:
      onlyIndices:
        description: 'Only run tests for the given indices (comma-separated)'
        required: false
        type: string
        default: ''

permissions:
  contents: read
  checks: write

jobs:
  run-comparison:
    name: Compare Pure and SKIE
    concurrency: ci-compare-tests-${{ github.ref }}
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.SWIFTPOET_TOKEN }}
      - name: Prepare Worker
        uses: ./.github/actions/prepare-worker
      - name: Run External Libraries Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ':acceptance-tests:external-libraries:test :acceptance-tests:external-libraries:pureTest :acceptance-tests:external-libraries:comparePureAndSkie --continue'
        env:
          onlyIndices: ${{ github.event.inputs.onlyIndices }}
      - name: Upload Comparison Report (S3)
        uses: jakejarvis/s3-sync-action@master
        if: always()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_TOUCHLAB_DEPLOY_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_TOUCHLAB_DEPLOY_PRIVATE }}
          AWS_S3_BUCKET: 'skie-data'
          AWS_REGION: 'us-east-2'
          SOURCE_DIR: 'acceptance-tests/external-libraries/build/reports/comparison-report.csv'
          DEST_DIR: 'comparison-reports/report-${{ github.run_id }}.csv'
      - name: Upload Comparison Report (GitHub artifact)
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: 'Comparison Report'
          path: 'acceptance-tests/external-libraries/build/reports/comparison-report.csv'
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: "Comparison Report"
          report_paths: 'acceptance-tests/external-libraries/build/test-results/comparePureAndSkie/TEST-*.xml'
          require_tests: true
          include_passed: true
          update_check: true
          annotate_only: true
          detailed_summary: true
