name: Import Analytics To Mixpanel

on:
  workflow_dispatch:

permissions:
  contents: read
  checks: write

concurrency:
  group: ci-import-analytics

jobs:
  import-analytics:
    name: Import Analytics
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Prepare Worker
        uses: ./.github/actions/prepare-worker
      - name: Run Acceptance Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ':dev-support:analytics:uploadAnalyticsToMixpanel'
        env:
          AWS_TOUCHLAB_DEPLOY_ACCESS: ${{ secrets.AWS_TOUCHLAB_DEPLOY_ACCESS }}
          AWS_TOUCHLAB_DEPLOY_SECRET: ${{ secrets.AWS_TOUCHLAB_DEPLOY_PRIVATE }}
          ANALYTICS_PRIVATE_KEY: ${{ secrets.ANALYTICS_PRIVATE_KEY }}
          MIXPANEL_PROJECT: ${{ secrets.MIXPANEL_PROJECT }}
          MIXPANEL_USERNAME: ${{ secrets.MIXPANEL_USERNAME }}
          MIXPANEL_PASSWORD: ${{ secrets.MIXPANEL_PASSWORD }}
