name: Publish Plugin

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  gradle:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    env:
      RELEASE_VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Cache Gradle Caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/**.gradle*', '**/gradle/wrapper/gradle-wrapper.properties', '**/libs.versions.toml') }}
      - name: Run Gradle tasks
        run: ./gradlew preMerge --continue
      - name: Publish on GitHub packages
        run: ./gradlew --project-dir plugin-build publishAllPublicationsToGitHubRepository
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish on Plugin Portal
        run: ./gradlew --project-dir plugin-build setupPluginUploadFromEnvironment publishPlugins
        if: ${{ false }} #success()
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: Stop Gradle
        run: ./gradlew --stop
