name: Publish Plugin

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  gradle:
    runs-on: macos-latest
    permissions:
      contents: read
      packages: write
    env:
      RELEASE_VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Cache Gradle Caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/**.gradle*', '**/gradle/wrapper/gradle-wrapper.properties', '**/libs.versions.toml') }}
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      - name: Run Gradle tasks
        run: ./gradlew preMerge --continue
      - name: Publish on AWS
        run: ./gradlew --project-dir swiftpack-plugin publishAllPublicationsToAwsRepository
        if: ${{ success() }}
        env:
          AWS_TOUCHLAB_DEPLOY_ACCESS: ${{ secrets.AWS_TOUCHLAB_DEPLOY_ACCESS }}
          AWS_TOUCHLAB_DEPLOY_SECRET: ${{ secrets.AWS_TOUCHLAB_DEPLOY_SECRET }}
      - name: Publish on Plugin Portal
        run: ./gradlew --project-dir swiftpack-plugin setupPluginUploadFromEnvironment publishPlugins
        if: ${{ false }} #success()
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: Stop Gradle
        if: always()
        run: ./gradlew --stop
