name: Publish Plugin

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[a-zA-Z0-9]*'

jobs:
  gradle:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    env:
      RELEASE_VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11
      # TODO Ensure all tests pass
      - name: Publish to Maven Central
        run: ./gradlew --project-dir SKIE publishToSonatype closeSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ""
