name: Smoke Tests on Push

on:
  push:
    branches:
      - main

permissions:
  contents: read
  checks: write

jobs:
  run-all-tests:
    uses: ./.github/workflows/all-tests.yml
    with:
      concurrency-id: smoke
    secrets: inherit
